github: FabioLolix
patreon: FabioLolix
ko_fi: fabiololix
liberapay: FabioLolix
custom: "https://www.paypal.com/donate?hosted_button_id=NJT3H9QXE4TWU"
custom: "https://buymeacoffee.com/FabioLoli"
custom: "https://sponsus.org/u/fabiololix"
custom: "https://en.tipeee.com/fabiololix"
